model = "MiniMax-M2.5"

# Model used by the /review feature (code reviews). Default: "gpt-5.1-codex-max".
review_model = "kimi-k2.5"

model_context_window = 128000

# Provider id selected from [model_providers]. Default: "openai".
model_provider = "newapi"

approval_policy = "on-request"
sandbox_mode = "danger-full-access"

web_search = "disabled"
personality = "pragmatic"

[defaults]
network_access = "enabled"

[sandbox_workspace_write]
network_access = true

[features]

[model_providers]
# not working
[model_providers.volc]
name = "Volcengine"
base_url = "https://ark.cn-beijing.volces.com/api/v3"
wire_api = "responses"
env_key = "VOLCENGINE_API_KEY"

# not working
[model_providers.newapi]
name = "NewAPI"
base_url = "https://newapi.gkzhb.top/v1"
# wire_api = "responses"
wire_api = "chat"
env_key = "NEWAPI_API_KEY"

[profiles]
[profiles.default]
model = "kimi-k2-250905"
model_provider = "volc"

